version: '3.8'

services:
  db:
    image: postgres:15
    container_name: vigileos_db
    environment:
      - POSTGRES_DB=vigileos
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vigileos_network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: vigileos_backend
    depends_on:
      - db
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-key
      - ALLOWED_HOSTS=localhost,127.0.0.1,147.93.94.81,vigileospro.com
      - POSTGRES_DB=vigileos
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - vigileos_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vigileos_frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - vigileos_network

networks:
  vigileos_network:
    driver: bridge

volumes:
  postgres_data:
